# Docker Compose for same-host deployment with existing Ollama
# Uses Ollama service already running on the host (no Ollama container)
# MongoDB and other services run in containers

services:
  # Frontend with integrated nginx (serves both static files and proxies backend)
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-}
        GIT_COMMIT: ${GIT_COMMIT:-}
        CACHE_BUST: ${CACHE_BUST:-}
    container_name: olympian-frontend
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      DEPLOYMENT_MODE: same-host-existing-ollama
      BACKEND_HOST: backend
      BACKEND_PORT: 4000
    depends_on:
      - backend
    networks:
      - olympian-network
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: olympian-backend
    restart: unless-stopped
    environment:
      DEPLOYMENT_MODE: same-host-existing-ollama
      MONGODB_URI: mongodb://olympian-mongodb:27017/olympian_ai_lite
      OLLAMA_HOST: http://host.docker.internal:11434
      # Model capability configuration for subproject 2
      MODEL_CAPABILITY_MODE: ${MODEL_CAPABILITY_MODE:-automatic}
      NODE_ENV: production
      PORT: 4000
      LOG_LEVEL: ${LOG_LEVEL:-info}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      RUNNING_IN_DOCKER: "true"
    volumes:
      - config-data:/config/.olympian-ai-lite
      - logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - olympian-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  # Database service only (Ollama runs on host)
  mongodb:
    image: mongo:7
    container_name: olympian-mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: olympian_ai_lite
    networks:
      - olympian-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Example MCP server
  mcp-filesystem:
    image: node:20-alpine
    container_name: olympian-mcp-filesystem
    restart: unless-stopped
    working_dir: /app
    command: npx -y @modelcontextprotocol/server-filesystem /data
    volumes:
      - mcp-data:/data
    networks:
      - olympian-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  config-data:
  logs:
  mongodb-data:
  mcp-data:

networks:
  olympian-network:
    driver: bridge
