version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: olympian-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: olympian_ai_lite

  ollama:
    image: ollama/ollama:latest
    container_name: olympian-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  mongodb_data:
  ollama_data: